batch_size: 8
lr: 0.0001
epochs: 250
patience: 15
checkpoints: "/work/oortega/checkpoints/vqvae/"
train_ratio: 0.8
beta_kl_loss: 0.001
device: "cuda"
architecture: "cuda"
dataset_path: "/data/oortega/pineapple_960x544.h5"
resize_img: 256
wandb_project: "dual_vae"
wandb_entity: "osco-itcr"
seed: 42
codebook_dim: 64
num_embeddings: 128
commitment_cost: 0.25
